### PR TITLE
Feature 01: MongoDB Skeleton

### PR DESCRIPTION
**Pull request by JeewakaSankalpa**
Request to add the Basic DBHandler class

- [ ] Create a test cases for CRUD (Create, Read, Update, and Delete)

- [ ] Run Coverage

### CODE REVIEW

**Comment by JeewakaSankalpa** [comment]
My resent commits weren't pushed to this one after we changed it to public. Any idea how to fix it?

**Comment by jaehoonhwang** [comment]
you need to change the remote base.
Easiest way to do just delete the repository (save the work)
Then commit again.

2nd Easiest way is to rebase.

**Comment by JeewakaSankalpa** [comment]
Something is wrong with the Fork I created earlier. It  was converted to a private repository when we changed this to public. When I re-based it it removed some of my files. 

I'll show it to you Thursday so you can check and help me fix it. 

Progress So Far-

---- Finished implementing basic test Cases as well as functions for all CRUD  with Doc Strings
---- Ran Coverage with 95% overall coverage result

**Comment by jaehoonhwang** [comment]
Ok

**Comment by jaehoonhwang** [comment]
Closing in favor of #11

**Pull request closed without merging**
